name: gcs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.12
  - numpy>=1.20
  - astropy>=4.0
  - pyyaml>=5.1
  - gfortran>=11  # Critical for running the compiled code
  - pip
  - meson 
  - pytest
  - gcc
  - matplotlib>=3.5
  - jupyterlab>=4
  - h5py=3.11.0
  - ipykernel
  - scipy 
  - pip>=24.2
  - pip:
    - -e .

